# Generated by Django 4.2.6 on 2023-10-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_emaillog_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="processed_today",
            field=models.BooleanField(default=False),
        ),
    ]
